# Generated by Django 5.2 on 2025-07-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TexteLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('corps', models.TextField()),
                ('domaine', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('date_publication', models.DateField()),
                ('fichier_original', models.FileField(upload_to='lois/')),
            ],
        ),
    ]
