# Generated by Django 5.2 on 2025-07-30 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Audiencé', 'Audiencé'), ('Jugé', 'Jugé'), ('Clôturé', 'Clôturé')], max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_audience', models.DateField(blank=True, null=True)),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='dossiers/')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
