# Generated by Django 5.2 on 2025-08-13 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('citoyen', 'Citoyen'), ('juriste', 'Juriste')], default='citoyen', max_length=20, verbose_name='Rôle')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1, verbose_name='Sexe')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession')),
                ('bio', models.TextField(blank=True, verbose_name='Présentation')),
                ('photo', models.ImageField(blank=True, help_text='Photo de profil au format carré', null=True, upload_to='citoyen_photos/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil citoyen',
                'verbose_name_plural': 'Profils citoyens',
            },
        ),
        migrations.DeleteModel(
            name='Juriste',
        ),
        migrations.AlterModelOptions(
            name='juristeprofile',
            options={'verbose_name': 'Profil juriste', 'verbose_name_plural': 'Profils juristes'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Avis', 'verbose_name_plural': 'Avis sur juristes'},
        ),
        migrations.RemoveField(
            model_name='juristeprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='juristeprofile',
            name='speciality',
        ),
        migrations.AddField(
            model_name='juristeprofile',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='juristeprofile',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='juristeprofile',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, verbose_name='Spécialité'),
        ),
        migrations.AddField(
            model_name='juristeprofile',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='juristeprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Présentation'),
        ),
        migrations.AlterField(
            model_name='juristeprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='juristeprofile',
            name='institution',
            field=models.CharField(blank=True, max_length=100, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='juristeprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo professionnelle au format carré idéalement', null=True, upload_to='juriste_photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='juristeprofile',
            name='profession',
            field=models.CharField(choices=[('Avocat', 'Avocat'), ('Magistrat', 'Magistrat'), ('Notaire', 'Notaire'), ('Huissier', 'Huissier')], max_length=30, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')], verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
