# Generated by Django 5.2 on 2025-07-30 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('categorie', models.CharField(max_length=100)),
                ('date_ajout', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentGeneré',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champs_remplis', models.JSONField()),
                ('pdf_fichier', models.FileField(upload_to='documents_generés/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.modeledocument')),
            ],
        ),
    ]
