# Generated by Django 5.2 on 2025-08-13 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='modeledocument',
            options={'ordering': ['-date_ajout'], 'verbose_name': 'Modèle de document', 'verbose_name_plural': 'Modèles de documents'},
        ),
        migrations.AddField(
            model_name='modeledocument',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='document',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='document',
            name='contenu',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='document',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='modeledocument',
            name='categorie',
            field=models.CharField(max_length=100, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='modeledocument',
            name='contenu',
            field=models.TextField(help_text='Utiliser {{ nom }}, {{ date }}, etc.', verbose_name='Contenu du modèle'),
        ),
        migrations.AlterField(
            model_name='modeledocument',
            name='date_ajout',
            field=models.DateField(auto_now_add=True, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='modeledocument',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom du modèle'),
        ),
        migrations.CreateModel(
            name='DocumentGenere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_document', models.CharField(choices=[('contrat', 'Contrat'), ('statuts', 'Statuts de société'), ('mise_en_demeure', 'Lettre de mise en demeure'), ('testament', 'Testament'), ('procuration', 'Procuration'), ('affidavit', 'Affidavit'), ('engagement', 'Acte d’engagement'), ('convention', 'Convention'), ('declaration', 'Déclaration sur l’honneur'), ('attestation', 'Attestation'), ('certificat', 'Certificat'), ('autorisation', 'Autorisation'), ('demande', 'Lettre de demande'), ('notification', 'Notification officielle'), ('reçu', 'Reçu de paiement'), ('passeport', 'Demande de passeport'), ('carte_identite', 'Demande de carte d’identité'), ('extrait_naissance', 'Extrait d’acte de naissance'), ('casier_judiciaire', 'Demande de casier judiciaire'), ('rapport', 'Rapport'), ('memo', 'Note ou mémo'), ('recommandation', 'Lettre de recommandation'), ('plainte', 'Plainte'), ('convocation', 'Convocation'), ('avis', 'Avis officiel'), ('ordre_mission', 'Ordre de mission'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Type de document')),
                ('champs_remplis', models.JSONField(verbose_name='Champs remplis')),
                ('pdf_fichier', models.FileField(blank=True, null=True, upload_to='documents_generes/', verbose_name='Fichier PDF généré')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('est_signe', models.BooleanField(default=False, verbose_name='Signé électroniquement')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('modele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.modeledocument', verbose_name='Modèle utilisé')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Document généré',
                'verbose_name_plural': 'Documents générés',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.DeleteModel(
            name='DocumentGeneré',
        ),
    ]
