# Generated by Django 5.2 on 2025-08-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleactualite',
            options={'ordering': ['-date_publication'], 'verbose_name': "Article d'actualité", 'verbose_name_plural': "Articles d'actualités"},
        ),
        migrations.AlterField(
            model_name='articleactualite',
            name='auteur',
            field=models.CharField(max_length=100, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='articleactualite',
            name='categorie',
            field=models.CharField(max_length=100, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='articleactualite',
            name='contenu',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='articleactualite',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='articleactualite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actualites/', verbose_name='Image illustratrice'),
        ),
        migrations.AlterField(
            model_name='articleactualite',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
    ]
