# Generated by Django 5.2 on 2025-08-13 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userprofile_delete_juriste_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.URLField()),
                ('date', models.DateTimeField()),
                ('statut', models.CharField(choices=[('prévu', 'Prévu'), ('en_cours', 'En cours'), ('terminé', 'Terminé'), ('annulé', 'Annulé')], default='prévu', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('juriste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels_video', to='accounts.juristeprofile')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels_video', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('est_payante', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('répondue', 'Répondue'), ('fermée', 'Fermée')], default='ouverte', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmé', 'Confirmé'), ('annulé', 'Annulé'), ('terminé', 'Terminé')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('juriste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdvs', to='accounts.juristeprofile')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Réponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('juriste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.juristeprofile')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='réponse', to='consultation.question')),
            ],
        ),
    ]
